name: First Workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "hello world Ubuntu"
      - name: Print bye
        run: echo "Bye ubu"
